Repository faast-rt/docs, pull requests merged in 2023-10, with the labels that each got.

#2 feat: add landing page
  components/cta.tsx
  components/features.tsx
  components/hero.tsx
  components/testimonials.tsx
  package.json
  pages/index.mdx
  pnpm-lock.yaml
  public/images/features-bg.png
  public/images/logos/polycode.png
  public/images/logos/polytech-montpellier.png
  public/images/testimonial.jpg
  style.css
Labels: enhancement, good first issue

#4 feat(ci): add conventional commits check
  .github/workflows/check.yaml
Labels: enhancement

#3 feat: add landing page image
  components/features.tsx
  public/images/features-1.png
  public/images/features-2.png
  public/images/features-3.png
Labels: documentation, enhancement

#5 feat: improve theme configuration
  theme.config.tsx
Labels: documentation, enhancement
